DROP TABLE IF EXISTS visits CASCADE;
DROP TABLE IF EXISTS specialties CASCADE;
DROP TABLE IF EXISTS vet_specialties CASCADE;
DROP TABLE IF EXISTS vets CASCADE;
DROP TABLE IF EXISTS pets CASCADE;
DROP TABLE IF EXISTS types CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    username VARCHAR(20)          NOT NULL,
    password VARCHAR(20)          NOT NULL,
    enabled  BOOLEAN DEFAULT TRUE NOT NULL,
    fullname VARCHAR(256)         NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE roles
(
    id       integer generated by default as identity,
    username VARCHAR(20) NOT NULL REFERENCES users (username),
    role     VARCHAR(20) NOT NULL,
    primary key (id)
);
CREATE INDEX fk_username_idx ON roles (username);


CREATE TABLE vets
(
    id       integer generated by default as identity,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    primary key (id)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties
(
    id       integer generated by default as identity,
    name VARCHAR(80),
    primary key (id)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties
(
    vet_id       INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL
);

alter table vet_specialties
    add constraint vet_specialties_to_vet_fk
        foreign key (vet_id)
            references vets;

alter table vet_specialties
    add constraint vet_specialties_to_specialties_fk
        foreign key (specialty_id)
            references specialties;

CREATE TABLE types
(
    id       integer generated by default as identity,
    name VARCHAR(80),
    primary key (id)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners
(
    id       integer generated by default as identity,
    first_name VARCHAR(30),
    last_name  VARCHAR(30),
    address    VARCHAR(255),
    city       VARCHAR(255),
    telephone  VARCHAR(128),
    primary key (id)
);
CREATE INDEX owners_last_name ON owners (lower(last_name));

CREATE TABLE pets
(
    id       integer generated by default as identity,
    name       VARCHAR(30),
    birth_date DATE,
    type_id    INTEGER NOT NULL REFERENCES types (id),
    owner_id   INTEGER NOT NULL REFERENCES owners (id),
    primary key (id)
);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits
(
    id       integer generated by default as identity,
    pet_id      INTEGER NOT NULL REFERENCES pets (id),
    vet_id      INTEGER REFERENCES vets (id),
    visit_date  DATE,
    description VARCHAR(255),
    primary key (id)
);
CREATE INDEX visits_pet_id ON visits (pet_id);
